version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '4306:3306'
    networks:
      - default
    volumes:
      - .mysql-data:/var/lib/mysql


  web:
    build: .
#    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
  swagger:
     image: swaggerapi/swagger-editor
     ports:
       - '80:8080'

volumes:
  mysql-data:
    driver: local